# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: update-github-client-ui
on:
  workflow_dispatch:
    inputs:
      source_commit_sha:
        description: ''
        required: false
        default: 'latest'
      debug_enabled:
        type: boolean
        description: ''
        required: false
        default: false
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  publish:
    defaults:
      run:
        shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Client Repository
        uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
        with:
          repository: richardsnider/github-client
          ref: ${{ github.event.inputs.source_commit_sha }}
          path: github_client_repo
      - name: Build Artifact
        run: |
          cd github_client_repo
          npm install
          npm run build
      - name: Checkout Github Pages Repository
        uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
        with:
          path: github_pages_repo
      - name: Add Artifact and Create an Update Branch
        run: |
          cp $GITHUB_WORKSPACE/github_client_repo/dist/* $GITHUB_WORKSPACE/github_pages_repo
          cd $GITHUB_WORKSPACE/github_pages_repo
          sed --in-place 's/__GITHUB_USERNAME__/richardsnider/g' ./index.html
          sed --in-place 's/__LINKEDIN_USERNAME__/richardsnider/g' ./index.html
          git checkout -b github-client-update-${{ github.event.inputs.source_commit_sha }}
          git config user.email "actions@github.com"
          git config user.name "Actions User"
          git commit -am "Update from github-client"
          git push origin github-client-update-${{ github.event.inputs.source_commit_sha }}
      - name: Debugger
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && github.event.inputs.debug_enabled }}