# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: update-github-client-ui
on:
  workflow_dispatch:
    inputs:
      source_commit_sha:
        description: ''
        required: false
        default: 'latest'
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  publish:
    defaults:
      run:
        shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
        with:
          repository: richardsnider/github-client
          ref: ${{ event.inputs.source_commit_sha }}
          path: source_code_repo
      - run: |
          cd source_code_repo
          npm install
          export GITHUB_USERNAME=richardsnider
          export LINKEDIN_USERNAME=richardsnider
          npm run build
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
        with:
          path: github_pages_repo
      - run: |
          cp $GITHUB_WORKSPACE/source_code_repo/dist/* $GITHUB_WORKSPACE/github_pages_repo
          git checkout -b github-client-${{ event.inputs.source_commit_sha }}
          git commit -am "Update from github-client"
          git push origin main
          gh pr create github-client-${{ event.inputs.source_commit_sha }}
